### ISSUE TITLE
focus should be on the newly opened file instead of the sidebar

### ISSUE THREAD

**Issue by mattsawyer77** [DeanNonatomic/atom-auto-reveal-in-sidebar#1]
This package works very well. Just a nit: after the file is revealed in the sidebar, the focus should move back to the window with the file's contents.

**Comment by DeanNonatomic** [comment]
Good point :) will add that, thanks

**Comment by DeanNonatomic** [comment]
Fixed :)

**Comment by mattsawyer77** [comment]
thanks for the super fast fix!
