### ISSUE TITLE
Auto reveal active file

### ISSUE THREAD

**Issue by galori** [DeanNonatomic/atom-auto-reveal-in-sidebar#5]
This package would be more useful if the auto reveal also kicked in whenever you view a file, even if it was already opened. (not only when opening, but even just switching to, or focusing on, a file that was already opened.)

as in:
1. Open two files
2. Switch between the two tabs back & forth
3. It should continue auto revealing based on the active file, even though the file wasn't just opened.

I ended up using auto-reveal-active-file package instead because it does this.

**Comment by DeanNonatomic** [comment]
Kayone had submitted a pull request for this a while back, it's been merged in now and works in the latest version.
