### ISSUE TITLE
Tree view steals focus when switching between tabs

### ISSUE THREAD

**Issue by atombender** [DeanNonatomic/atom-auto-reveal-in-sidebar#7]
Recent regression, probably caused by [this](https://github.com/DeanNonatomic/atom-auto-reveal-in-sidebar/commit/8c4682dc0a5baaa54b2f3ec80cb71a6885be4d79) commit.

![screen capture on 2015-11-08 at 23-11-42](https://cloud.githubusercontent.com/assets/50314/11025814/60ae1e60-866e-11e5-9f1f-1cb609fda726.gif)

Here I'm hitting the "next tab" keyboard shortcut, which brings focus over to the tree view.

**Comment by maladon** [comment]
Yep! Concur with atombender. This is quite annoying. Using the keyboard to switch files (cmd-opt-left/right) causes focus to remain in treeview now. 

I added the code back in locally and it behaves as expected now.

**Comment by rmariuzzo** [comment]
This one is working without this issue: https://github.com/sfaedo/auto-reveal-active-file

**Comment by psimek12** [comment]
I have added this line to get the focus back to the file:

atom.commands.dispatch(workspaceView, 'enter');

**Comment by DeanNonatomic** [comment]
Think I've fixed it.

Took me long time to get around to sorting this, really sorry about that. Life is very hectic at the minute and if I'm brutally honest I've switched to VSCode anyway.

If anyone would like to take control of this repo, please get in touch. If not I'll try my best to keep it up to date and fix issues.

**Comment by littlebee** [comment]
Hi, I see you released a fix for this issue.  I'm not sure why, but my settings/install lists your most recent version as 0.8.0.  https://github.com/DeanNonatomic/atom-auto-reveal-in-sidebar/releases shows the latest as 0.10.0.   This package was working perfectly until I recently was upgraded to atom 1.17.0.
